
unit DataModuleMaster;

interface

uses
  SysUtils, Windows, Messages, Classes, Graphics, Controls, Forms,
  Dialogs, DBTables, DB, Wwdatsrc, ppDB, ppComm,
  ppRelatv, ppDBPipe, MemDS, DBAccess, Uni, QImport3, QImport3XLS;

type
  T_DataModuleMaster = class(TDataModule)
    MbankDS: TwwDataSource;
    MKecamatanDS: TwwDataSource;
    MKotaDS: TwwDataSource;
    Mbank: TUniTable;
    MKecamatan: TUniTable;
    MKota: TUniTable;
    MList_Depo: TUniTable;
    MList_DepoDS: TwwDataSource;
    MBagian: TUniTable;
    MBagianDS: TwwDataSource;
    MBagianBAGIAN: TStringField;
    MBagianKETERANGAN: TStringField;
    MbankKETERANGAN: TStringField;
    MbankKODE: TStringField;
    MbankNAMA_BANK: TStringField;
    MJabatan: TUniTable;
    MJabatanDS: TwwDataSource;
    MJabatanJABATAN: TStringField;
    MJabatanKETERANGAN: TStringField;
    MPendidikanDS: TwwDataSource;
    MKecamatanNAMA_KECAMATAN: TStringField;
    MKecamatanKETERANGAN: TStringField;
    Mkaryawan_all: TUniTable;
    Mkaryawan_allDS: TwwDataSource;
    Mkaryawan_allKODE: TStringField;
    Mkaryawan_allNIK: TStringField;
    Mkaryawan_allNAMA: TStringField;
    Mkaryawan_allFINGER_KODE: TStringField;
    Mkaryawan_allJENIS_PENGENAL: TStringField;
    Mkaryawan_allNOMOR_PENGENAL: TStringField;
    Mkaryawan_allALAMAT: TStringField;
    Mkaryawan_allKODE_POS: TStringField;
    Mkaryawan_allTELEPON: TStringField;
    Mkaryawan_allHANDPHONE: TStringField;
    Mkaryawan_allAGAMA: TStringField;
    Mkaryawan_allPENDIDIKAN: TStringField;
    Mkaryawan_allSTATUS: TStringField;
    Mkaryawan_allBAGIAN: TStringField;
    Mkaryawan_allJABATAN: TStringField;
    Mkaryawan_allIS_AKTIF: TStringField;
    Mkaryawan_allJENIS_KELAMIN: TStringField;
    Mkaryawan_allNAMA_BANK: TStringField;
    Mkaryawan_allNO_REKENING: TStringField;
    Mkaryawan_allNAMA_PASANGAN: TStringField;
    Mkaryawan_allNAMA_ANAK_1: TStringField;
    Mkaryawan_allNAMA_ANAK_2: TStringField;
    Mkaryawan_allNAMA_ANAK_3: TStringField;
    Mkaryawan_allKOTA: TStringField;
    Mkaryawan_allKECAMATAN: TStringField;
    Mkaryawan_AktifDS: TwwDataSource;
    Mkaryawan_Aktif: TUniQuery;
    Mkaryawan_AktifKODE: TStringField;
    Mkaryawan_AktifNIK: TStringField;
    Mkaryawan_AktifNAMA: TStringField;
    Mkaryawan_AktifFINGER_KODE: TStringField;
    Mkaryawan_AktifJENIS_PENGENAL: TStringField;
    Mkaryawan_AktifNOMOR_PENGENAL: TStringField;
    Mkaryawan_AktifALAMAT: TStringField;
    Mkaryawan_AktifKODE_POS: TStringField;
    Mkaryawan_AktifTELEPON: TStringField;
    Mkaryawan_AktifHANDPHONE: TStringField;
    Mkaryawan_AktifAGAMA: TStringField;
    Mkaryawan_AktifPENDIDIKAN: TStringField;
    Mkaryawan_AktifSTATUS: TStringField;
    Mkaryawan_AktifBAGIAN: TStringField;
    Mkaryawan_AktifJABATAN: TStringField;
    Mkaryawan_AktifIS_AKTIF: TStringField;
    Mkaryawan_AktifJENIS_KELAMIN: TStringField;
    Mkaryawan_AktifNAMA_BANK: TStringField;
    Mkaryawan_AktifNO_REKENING: TStringField;
    Mkaryawan_AktifNAMA_PASANGAN: TStringField;
    Mkaryawan_AktifNAMA_ANAK_1: TStringField;
    Mkaryawan_AktifNAMA_ANAK_2: TStringField;
    Mkaryawan_AktifNAMA_ANAK_3: TStringField;
    Mkaryawan_AktifKOTA: TStringField;
    Mkaryawan_AktifKECAMATAN: TStringField;
    MPendidikan: TUniTable;
    Mgrading: TUniTable;
    MgradingDS: TwwDataSource;
    MgradingGRADE: TStringField;
    MgradingGAPOK: TFloatField;
    MgradingTRANSPORT: TFloatField;
    MgradingAKOMODASI: TFloatField;
    MgradingTUNJANGAN: TFloatField;
    MgradingKENDARAAN: TFloatField;
    MgradingBONUS: TFloatField;
    MgradingPROSENTASE_KENAIKAN: TFloatField;
    Mgrading_List: TUniTable;
    StringField1: TStringField;
    FloatField1: TFloatField;
    FloatField2: TFloatField;
    FloatField3: TFloatField;
    FloatField4: TFloatField;
    FloatField5: TFloatField;
    FloatField6: TFloatField;
    Mgrading_ListDS: TwwDataSource;
    Mgrading_ListPROSENTASE_KENAIKAN: TFloatField;
    Mgrading_ListGRADE_LEVEL: TIntegerField;
    Mgrading_ListTOTAL_ALL: TLargeintField;
    wwDataSource1: TwwDataSource;
    Mgrading_ListTOTAL_REAL: TLargeintField;
    MDivisi: TUniTable;
    MDivisiDS: TwwDataSource;
    MDivisiDIVISI: TStringField;
    MDivisiKETERANGAN: TStringField;
    Mbrand: TUniTable;
    MbrandDS: TwwDataSource;
    MbrandBRAND: TStringField;
    MbrandKETERANGAN: TStringField;
    Mkaryawan_allDIVISI: TStringField;
    Mkaryawan_allBRAND: TStringField;
    Mgrading_List_All: TUniQuery;
    Mgrading_List_AllGRADE: TStringField;
    Mgrading_List_AllGAPOK: TFloatField;
    Mgrading_List_AllTRANSPORT: TFloatField;
    Mgrading_List_AllAKOMODASI: TFloatField;
    Mgrading_List_AllTUNJANGAN: TFloatField;
    Mgrading_List_AllKENDARAAN: TFloatField;
    Mgrading_List_AllBONUS: TFloatField;
    Mgrading_List_AllPROSENTASE_KENAIKAN: TFloatField;
    Mgrading_List_AllGRADE_LEVEL: TIntegerField;
    Mgrading_List_AllTOTAL_ALL: TLargeintField;
    Mgrading_List_AllTOTAL_REAL: TLargeintField;
    List_Driver: TUniQuery;
    List_Driverszidsopir: TStringField;
    List_Driversznama_sopir: TStringField;
    List_DriverDS: TwwDataSource;
    List_Driverasal: TStringField;
    MProductDS: TwwDataSource;
    MgradingJENIS_VERSI: TStringField;
    MgradingJUMLAH_GENERATED: TIntegerField;
    MPendidikanPENDIDIKAN: TStringField;
    MPendidikanKETERANGAN: TStringField;
    Mkaryawan_allGRADE: TStringField;
    Mkaryawan_allGRADE_LEVEL: TIntegerField;
    Mkaryawan_allLDIVISI: TStringField;
    MList_DepoDEPO: TStringField;
    MList_DepoSKT_DEPO: TStringField;
    MList_DepoKETERANGAN: TStringField;
    MList_DepoNAMA_DEPO: TStringField;
    MList_DepoALAMAT: TStringField;
    MList_DepoJENIS: TStringField;
    MList_DepoNIK_KEPALA_DEPO: TStringField;
    MList_DepoKODE_ASM: TStringField;
    Area_SM: TUniTable;
    Area_SMDS: TwwDataSource;
    Area_SMKD_area_depo: TStringField;
    Area_SMnama_area_depo: TStringField;
    Area_SMnik_kepala_asm: TStringField;
    Area_SMLnama_kepala_ASM: TStringField;
    MList_DepoLnama_Kepala_Depo: TStringField;
    MList_DepoLketerangan_ASM: TStringField;
    MList_DepoLNama_Kepala_ASM: TStringField;
    Mkaryawan_AktifDIVISI: TStringField;
    Mkaryawan_AktifLnama_Divisi: TStringField;
    MGroup: TUniTable;
    MGroupDS: TwwDataSource;
    MUkuran: TUniTable;
    MUkuranDS: TwwDataSource;
    MUkuranUKURAN: TStringField;
    MUkuranKETERANGAN: TStringField;
    MUkuranJUMLAH_PCS: TStringField;
    MKlasifikasi: TUniTable;
    MKlasifikasiDS: TwwDataSource;
    MKlasifikasiKLASIFIKASI: TStringField;
    MKlasifikasiNAMA_KLASIFIKASI: TStringField;
    MKlasifikasiKETERANGAN: TStringField;
    MGroupKD_GROUP: TStringField;
    MGroupKETERANGAN: TStringField;
    MWilayah: TUniTable;
    MWilayahDS: TwwDataSource;
    MKategori: TUniTable;
    MKategoriDS: TwwDataSource;
    MKategorikategori: TStringField;
    MKategorinama_kategori: TStringField;
    MKategoriketerangan: TStringField;
    MWilayahwilayah: TStringField;
    MWilayahnama_wilayah: TStringField;
    MWilayahketerangan: TStringField;
    MWilayahdepo: TStringField;
    mst_outletDS: TwwDataSource;
    MKotaKOTA: TStringField;
    MKotaKETERANGAN: TStringField;
    MST_OUTLET: TUniQuery;
    MST_OUTLETKODE: TStringField;
    MST_OUTLETNAMA: TStringField;
    MST_OUTLETSINGKATAN: TStringField;
    MST_OUTLETALAMAT_1: TStringField;
    MST_OUTLETALAMAT_2: TStringField;
    MST_OUTLETTELP_1: TStringField;
    MST_OUTLETTELP_2: TStringField;
    MST_OUTLETFAX: TStringField;
    MST_OUTLETEMAIL: TStringField;
    MST_OUTLETKODE_POS: TStringField;
    MST_OUTLETKECAMATAN: TStringField;
    MST_OUTLETKOTA: TStringField;
    MST_OUTLETNAMA_PAJAK: TStringField;
    MST_OUTLETALAMAT_PAJAK_1: TStringField;
    MST_OUTLETALAMAT_PAJAK_2: TStringField;
    MST_OUTLETKODE_TRANSAKSI_PAJAK: TStringField;
    MST_OUTLETNPWP: TStringField;
    MST_OUTLETALAMAT_KIRIM_1: TStringField;
    MST_OUTLETALAMAT_KIRIM_2: TStringField;
    MST_OUTLETKECAMATAN_KIRIM: TStringField;
    MST_OUTLETKOTA_KIRIM: TStringField;
    MST_OUTLETIS_ALAMAT_KIRIM_SAMA: TStringField;
    MST_OUTLETCONTACT_PERSON: TStringField;
    MST_OUTLETTELP_CP: TStringField;
    MST_OUTLETKREDIT_LIMIT: TIntegerField;
    MST_OUTLETwilayah: TStringField;
    MST_OUTLETkategori: TStringField;
    MST_OUTLETsales_representatif_nik: TWideStringField;
    MST_OUTLETpenagih_nik: TWideStringField;
    MST_OUTLETklasifikasi_ar: TStringField;
    MST_OUTLETcut_off_saldo_piutang_nilai: TIntegerField;
    MST_OUTLETcut_off_saldo_hutang_nilai: TIntegerField;
    MST_OUTLETdepo: TStringField;
    MST_OUTLETis_aktif: TStringField;
    MST_OUTLETAlasan_non_aktif: TStringField;
    MST_OUTLETbarcode: TStringField;
    MST_OUTLETis_black_list: TStringField;
    MST_OUTLETAlasan_Black_list: TStringField;
    MST_OUTLETLsales_representatif_NAMA: TStringField;
    MST_OUTLETLPenagih_NAMA: TStringField;
    MST_OUTLETLWILAYAH_NAMA: TStringField;
    MST_OUTLETLKATEGORI_NAMA: TStringField;
    MST_OUTLET_aktif: TUniQuery;
    StringField3: TStringField;
    StringField4: TStringField;
    StringField5: TStringField;
    StringField6: TStringField;
    StringField7: TStringField;
    StringField8: TStringField;
    StringField9: TStringField;
    StringField10: TStringField;
    StringField11: TStringField;
    StringField12: TStringField;
    StringField13: TStringField;
    StringField14: TStringField;
    StringField15: TStringField;
    StringField16: TStringField;
    StringField17: TStringField;
    StringField18: TStringField;
    StringField19: TStringField;
    StringField20: TStringField;
    StringField21: TStringField;
    StringField22: TStringField;
    StringField23: TStringField;
    StringField24: TStringField;
    StringField25: TStringField;
    IntegerField1: TIntegerField;
    StringField26: TStringField;
    StringField27: TStringField;
    WideStringField2: TWideStringField;
    StringField28: TStringField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    StringField29: TStringField;
    StringField30: TStringField;
    StringField31: TStringField;
    StringField32: TStringField;
    StringField33: TStringField;
    StringField34: TStringField;
    StringField35: TStringField;
    StringField36: TStringField;
    StringField37: TStringField;
    StringField38: TStringField;
    MST_OUTLET_aktifDS: TwwDataSource;
    MST_OUTLET_aktifKODE: TStringField;
    M_KendaraanDS: TwwDataSource;
    Mkendaraan: TUniQuery;
    MkendaraanNO_POLISI: TStringField;
    MkendaraanKODE: TStringField;
    MkendaraanJENIS: TStringField;
    MkendaraanWARNA: TStringField;
    MkendaraanTAHUN: TStringField;
    MkendaraanMERK: TStringField;
    MkendaraanKAPASITAS_ANGKUT: TSmallintField;
    MkendaraanSOPIR: TStringField;
    MkendaraanPENANGGUNG_JAWAB: TStringField;
    MkendaraanIS_AKTIF: TStringField;
    MkendaraanTYPE_KENDARAAN: TStringField;
    MkendaraanATAS_NAMA: TStringField;
    MkendaraanNO_RANGKA: TStringField;
    MkendaraanNO_MESIN: TStringField;
    MkendaraanNO_BPKB: TStringField;
    MkendaraanBUKU_KIR: TStringField;
    MkendaraanTAHUN_MOBIL: TStringField;
    MkendaraanDIVISI: TStringField;
    MkendaraanID_EKSPEDISI: TSmallintField;
    MkendaraanNIK_HRIS: TStringField;
    MkendaraanKODE_DMS: TStringField;
    MkendaraanTARGET: TIntegerField;
    MkendaraanNILAI_INCENTIVE: TIntegerField;
    MkendaraanBRAND: TStringField;
    MkendaraanALAMAT_PEMILIK: TStringField;
    MkendaraanISI_SILINDER: TStringField;
    MkendaraanKETERANGAN: TStringField;
    MkendaraanFUNGSIONAL: TStringField;
    Mkendaraandepo: TStringField;
    Lks_gudang: TUniQuery;
    Lks_gudangDS: TwwDataSource;
    Lks_gudangkode: TStringField;
    Lks_gudanggudang: TStringField;
    Lks_gudangSINGKATAN: TStringField;
    Lks_gudangdepo: TStringField;
    Lks_gudangis_aktif: TStringField;
    Mkendaraankapasitas_angkut_liter: TIntegerField;
    Mkendaraansts_kepemilikan: TStringField;
    MST_OUTLET_aktifsales_representatif_nik: TWideStringField;
    Maccount: TUniTable;
    MaccountDS: TwwDataSource;
    Maccountno_account: TStringField;
    Maccountketerangan: TStringField;
    Maccounttipe: TStringField;
    Maccountcost_center: TStringField;
    Maccountproyek: TStringField;
    Maccountdebitur_or_kreditur: TStringField;
    Maccountis_aktif: TStringField;
    Mbiaya_pendapatan: TUniTable;
    Mbiaya_pendapatanDS: TwwDataSource;
    Mbiaya_pendapatankode: TStringField;
    Mbiaya_pendapatanketerangan: TStringField;
    Mbiaya_pendapatansingkatan: TStringField;
    Mbiaya_pendapatanno_account: TStringField;
    Mbiaya_pendapatantipe_cost_center: TStringField;
    Mbiaya_pendapatantgl_non_aktif: TDateField;
    Mbiaya_pendapatanis_aktif: TStringField;
    Mbiaya_pendapatanLnama_Account: TStringField;
    MBIAYA_PENDAPATAN_AKTIF: TUniQuery;
    MBIAYA_PENDAPATAN_AKTIFDS: TwwDataSource;
    MBIAYA_PENDAPATAN_AKTIFkode: TStringField;
    MBIAYA_PENDAPATAN_AKTIFketerangan: TStringField;
    MBIAYA_PENDAPATAN_AKTIFsingkatan: TStringField;
    MBIAYA_PENDAPATAN_AKTIFno_account: TStringField;
    MBIAYA_PENDAPATAN_AKTIFtipe_cost_center: TStringField;
    MBIAYA_PENDAPATAN_AKTIFis_aktif: TStringField;
    MBIAYA_PENDAPATAN_AKTIFNAMA_ACCOUNT: TStringField;
    MProduct: TUniQuery;
    ZMUSERTRE: TUniQuery;
    MST_OUTLETTGL_AKTIF: TDateTimeField;
    MST_OUTLETcut_off_saldo_piutang_tanggal: TDateTimeField;
    MST_OUTLETcut_off_saldo_hutang_tanggal: TDateTimeField;
    MST_OUTLETtgl_non_aktif: TDateTimeField;
    MST_OUTLET_aktifTGL_AKTIF: TDateTimeField;
    MST_OUTLET_aktifcut_off_saldo_piutang_tanggal: TDateTimeField;
    MST_OUTLET_aktifcut_off_saldo_hutang_tanggal: TDateTimeField;
    MST_OUTLET_aktiftgl_non_aktif: TDateTimeField;
    Mkaryawan_allTGL_LAHIR: TDateTimeField;
    Mkaryawan_allTGL_AWAL_KERJA: TDateTimeField;
    Mkaryawan_allTGL_AKHIR_KERJA: TDateTimeField;
    Mkaryawan_allSTATUS_PPH_21: TStringField;
    Mkaryawan_allTGL_LAHIR_PASANGAN: TDateTimeField;
    Mkaryawan_allTGL_LAHIR_ANAK_1: TDateTimeField;
    Mkaryawan_allTGL_LAHIR_ANAK_2: TDateTimeField;
    Mkaryawan_allTGL_LAHIR_ANAK_3: TDateTimeField;
    Mkaryawan_allPOT_JAMSOSTEK: TIntegerField;
    Mkaryawan_allKODE_DMS: TStringField;
    Mkaryawan_allINCENTIVE_KODE_SKEMA_AO: TStringField;
    Mkaryawan_allINCENTIVE_IS_GUDANG: TStringField;
    Mkaryawan_allNIK_SOPIR: TStringField;
    Mkaryawan_allJENIS_KENDARAAN: TStringField;
    Mkaryawan_allNilai_TARGET: TIntegerField;
    Mkaryawan_allIS_VALID: TStringField;
    Mkaryawan_allUSER_INSERT: TStringField;
    Mkaryawan_allTGL_INSERT: TDateTimeField;
    Mkaryawan_allUSER_EDIT: TStringField;
    Mkaryawan_allTGL_EDIT: TDateTimeField;
    Mkaryawan_allUSER_DELETE: TStringField;
    Mkaryawan_allTGL_DELETE: TDateTimeField;
    Mkaryawan_allSTATUS_KAWIN: TStringField;
    Mkaryawan_allNO_NPWP: TStringField;
    Mkaryawan_allNO_JAMSOSTEK: TStringField;
    Mkaryawan_allJHT: TIntegerField;
    Mkaryawan_allJKM: TIntegerField;
    Mkaryawan_allJKK: TIntegerField;
    Mkaryawan_allJPK: TIntegerField;
    Mkaryawan_allIURAN_JAMSOSTEK: TIntegerField;
    Mkaryawan_AktifTGL_LAHIR: TDateTimeField;
    Mkaryawan_AktifTGL_AWAL_KERJA: TDateTimeField;
    Mkaryawan_AktifTGL_AKHIR_KERJA: TDateTimeField;
    Maccounttgl_non_aktif: TDateTimeField;
    MkendaraanTGL_PAJAK: TDateTimeField;
    MkendaraanTGL_STNK: TDateTimeField;
    MkendaraanTGL_KIR: TDateTimeField;
    MkendaraanTGL_PEMBELIAN: TDateTimeField;
    MBIAYA_PENDAPATAN_AKTIFtgl_non_aktif: TDateTimeField;
    MST_OUTLETis_tunai: TStringField;
    MST_OUTLET_aktifis_tunai: TStringField;
    MList_DepoDepo_1: TStringField;
    Msetting_Account: TUniTable;
    Msetting_AccountDS: TwwDataSource;
    Msetting_AccountJENIS_TRANSAKSI: TStringField;
    Msetting_AccountNO_ACCOUNT: TStringField;
    Msetting_AccountLnama_Account: TStringField;
    Msetting_Accountkode_transaksi: TStringField;
    MST_SupplierDS: TwwDataSource;
    MST_SUPPLIER: TUniQuery;
    MST_SUPPLIER_AKTIF: TUniQuery;
    MST_SUPPLIER_AKTIFDS: TwwDataSource;
    MST_SUPPLIER_AKTIFKODE: TStringField;
    MST_SUPPLIER_AKTIFNAMA: TStringField;
    MST_SUPPLIER_AKTIFSINGKATAN: TStringField;
    MST_SUPPLIER_AKTIFALAMAT_1: TStringField;
    MST_SUPPLIER_AKTIFALAMAT_2: TStringField;
    MST_SUPPLIER_AKTIFTELP_1: TStringField;
    MST_SUPPLIER_AKTIFTELP_2: TStringField;
    MST_SUPPLIER_AKTIFFAX: TStringField;
    MST_SUPPLIER_AKTIFEMAIL: TStringField;
    MST_SUPPLIER_AKTIFKODE_POS: TStringField;
    MST_SUPPLIER_AKTIFKECAMATAN: TStringField;
    MST_SUPPLIER_AKTIFKOTA: TStringField;
    MST_SUPPLIER_AKTIFNAMA_PAJAK: TStringField;
    MST_SUPPLIER_AKTIFALAMAT_PAJAK_1: TStringField;
    MST_SUPPLIER_AKTIFALAMAT_PAJAK_2: TStringField;
    MST_SUPPLIER_AKTIFKODE_TRANSAKSI_PAJAK: TStringField;
    MST_SUPPLIER_AKTIFNPWP: TStringField;
    MST_SUPPLIER_AKTIFTGL_AKTIF: TDateTimeField;
    MST_SUPPLIER_AKTIFALAMAT_KIRIM_1: TStringField;
    MST_SUPPLIER_AKTIFALAMAT_KIRIM_2: TStringField;
    MST_SUPPLIER_AKTIFKECAMATAN_KIRIM: TStringField;
    MST_SUPPLIER_AKTIFKOTA_KIRIM: TStringField;
    MST_SUPPLIER_AKTIFIS_ALAMAT_KIRIM_SAMA: TStringField;
    MST_SUPPLIER_AKTIFCONTACT_PERSON: TStringField;
    MST_SUPPLIER_AKTIFTELP_CP: TStringField;
    MST_SUPPLIER_AKTIFKREDIT_LIMIT: TIntegerField;
    MST_SUPPLIER_AKTIFwilayah: TStringField;
    MST_SUPPLIER_AKTIFkategori: TStringField;
    MST_SUPPLIER_AKTIFsales_representatif_nik: TWideStringField;
    MST_SUPPLIER_AKTIFpenagih_nik: TWideStringField;
    MST_SUPPLIER_AKTIFklasifikasi_ar: TStringField;
    MST_SUPPLIER_AKTIFcut_off_saldo_piutang_nilai: TIntegerField;
    MST_SUPPLIER_AKTIFcut_off_saldo_hutang_nilai: TIntegerField;
    MST_SUPPLIER_AKTIFcut_off_saldo_piutang_tanggal: TDateTimeField;
    MST_SUPPLIER_AKTIFcut_off_saldo_hutang_tanggal: TDateTimeField;
    MST_SUPPLIER_AKTIFdepo: TStringField;
    MST_SUPPLIER_AKTIFis_aktif: TStringField;
    MST_SUPPLIER_AKTIFAlasan_non_aktif: TStringField;
    MST_SUPPLIER_AKTIFbarcode: TStringField;
    MST_SUPPLIER_AKTIFtgl_non_aktif: TDateTimeField;
    MST_SUPPLIER_AKTIFis_black_list: TStringField;
    MST_SUPPLIER_AKTIFAlasan_Black_list: TStringField;
    MST_SUPPLIER_AKTIFis_tunai: TStringField;
    MST_SUPPLIER_AKTIFkode_lama: TStringField;
    MST_SUPPLIER_AKTIFno_urut: TIntegerField;
    MST_SUPPLIER_AKTIFLsales_representatif_NAMA: TStringField;
    MST_SUPPLIER_AKTIFLPenagih_NAMA: TStringField;
    MST_SUPPLIER_AKTIFLWILAYAH_NAMA: TStringField;
    MST_SUPPLIER_AKTIFLKATEGORI_NAMA: TStringField;
    MProductNAMA_ITEM: TStringField;
    MProductSINGK_ITEM: TStringField;
    MProductBRAND: TStringField;
    MProductKD_GROUP: TStringField;
    MProductUKURAN: TStringField;
    MProductVOLUME: TFloatField;
    MProductBERAT: TFloatField;
    MProductMINIMUM_STOCK: TIntegerField;
    MProductIS_AKTIF: TStringField;
    MProductTGL_NON_AKTIF: TDateTimeField;
    MProductbarcode: TStringField;
    MProductSATUAN: TStringField;
    MST_SUPPLIERKODE: TStringField;
    MST_SUPPLIERNAMA: TStringField;
    MST_SUPPLIERSINGKATAN: TStringField;
    MST_SUPPLIERALAMAT_1: TStringField;
    MST_SUPPLIERALAMAT_2: TStringField;
    MST_SUPPLIERTELP_1: TStringField;
    MST_SUPPLIERTELP_2: TStringField;
    MST_SUPPLIERFAX: TStringField;
    MST_SUPPLIEREMAIL: TStringField;
    MST_SUPPLIERKODE_POS: TStringField;
    MST_SUPPLIERKECAMATAN: TStringField;
    MST_SUPPLIERKOTA: TStringField;
    MST_SUPPLIERNAMA_PAJAK: TStringField;
    MST_SUPPLIERALAMAT_PAJAK_1: TStringField;
    MST_SUPPLIERALAMAT_PAJAK_2: TStringField;
    MST_SUPPLIERKODE_TRANSAKSI_PAJAK: TStringField;
    MST_SUPPLIERNPWP: TStringField;
    MST_SUPPLIERTGL_AKTIF: TDateTimeField;
    MST_SUPPLIERALAMAT_KIRIM_1: TStringField;
    MST_SUPPLIERALAMAT_KIRIM_2: TStringField;
    MST_SUPPLIERKECAMATAN_KIRIM: TStringField;
    MST_SUPPLIERKOTA_KIRIM: TStringField;
    MST_SUPPLIERIS_ALAMAT_KIRIM_SAMA: TStringField;
    MST_SUPPLIERCONTACT_PERSON: TStringField;
    MST_SUPPLIERTELP_CP: TStringField;
    MST_SUPPLIERKREDIT_LIMIT: TIntegerField;
    MST_SUPPLIERwilayah: TStringField;
    MST_SUPPLIERkategori: TStringField;
    MST_SUPPLIERsales_representatif_nik: TWideStringField;
    MST_SUPPLIERpenagih_nik: TWideStringField;
    MST_SUPPLIERklasifikasi_ar: TStringField;
    MST_SUPPLIERcut_off_saldo_piutang_nilai: TIntegerField;
    MST_SUPPLIERcut_off_saldo_hutang_nilai: TIntegerField;
    MST_SUPPLIERcut_off_saldo_piutang_tanggal: TDateTimeField;
    MST_SUPPLIERcut_off_saldo_hutang_tanggal: TDateTimeField;
    MST_SUPPLIERdepo: TStringField;
    MST_SUPPLIERis_aktif: TStringField;
    MST_SUPPLIERAlasan_non_aktif: TStringField;
    MST_SUPPLIERbarcode: TStringField;
    MST_SUPPLIERtgl_non_aktif: TDateTimeField;
    MST_SUPPLIERis_black_list: TStringField;
    MST_SUPPLIERAlasan_Black_list: TStringField;
    MST_SUPPLIERis_tunai: TStringField;
    MST_SUPPLIERkode_lama: TStringField;
    MST_SUPPLIERno_urut: TIntegerField;
    MProductLKET_BRAND: TStringField;
    MProductLKET_GROUP: TStringField;
    MProductLKET_UKURAN: TStringField;
    MProductLPCS_UKURAN: TStringField;
    MProductLKET_KLASIFIKASI: TStringField;
    MProductJADWAL_PM: TStringField;
    Browse_Aset: TUniQuery;
    Browse_AsetKODE_ITEM: TStringField;
    Browse_AsetNAMA_ITEM: TStringField;
    Browse_AsetSINGK_ITEM: TStringField;
    Browse_AsetBRAND: TStringField;
    Browse_AsetKD_GROUP: TStringField;
    Browse_AsetUKURAN: TStringField;
    Browse_AsetVOLUME: TFloatField;
    Browse_AsetBERAT: TFloatField;
    Browse_AsetKLASIFIKASI: TStringField;
    Browse_AsetMINIMUM_STOCK: TIntegerField;
    Browse_AsetIS_AKTIF: TStringField;
    Browse_AsetTGL_NON_AKTIF: TDateTimeField;
    Browse_Asetbarcode: TStringField;
    Browse_AsetSATUAN: TStringField;
    Browse_AsetJADWAL_PM: TStringField;
    Browse_AsetDS: TwwDataSource;
    Browse_AsetLKET_BRAND: TStringField;
    Browse_AsetLKET_GROUP: TStringField;
    MDivisiItemDS: TwwDataSource;
    MDivisiItem: TUniTable;
    MProductDIVISI_ITEM: TStringField;
    MProductLKET_DIVISIITEM: TStringField;
    Browse_AsetLUkuran: TStringField;
    Browse_AsetDIVISI_ITEM: TStringField;
    Browse_AsetLKlasifikasi: TStringField;
    Browse_AsetLKET_DIVISIITEM: TStringField;
    Msatuan: TUniTable;
    Msatuands: TwwDataSource;
    Msatuankode_satuan: TStringField;
    Msatuannama_satuan: TStringField;
    Msatuanketerangan: TStringField;
    ZUserDepo: TUniQuery;
    List_Filter_Alfa: TUniQuery;
    List_Filter_AlfaList_Filter: TStringField;
    List_Filter_AlfaIs_Aktif: TStringField;
    List_Filter_Invoice: TUniTable;
    List_Filter_depoDS: TwwDataSource;
    List_Filter_InvoiceList_Filter: TStringField;
    List_Filter_InvoiceIs_Aktif: TStringField;
    Jenis_Permintaan: TUniTable;
    Jenis_PermintaanDS: TwwDataSource;
    Jenis_PermintaanJenis_Permintaan: TStringField;
    Mst_Periode: TUniTable;
    Mst_PeriodeDS: TwwDataSource;
    Mst_Periodeperiode_awal: TDateTimeField;
    Mst_Periodeperiode_akhir: TDateTimeField;
    Mst_Perioderesult_periode: TDateTimeField;
    List_Filter_Invoice_m: TUniTable;
    List_Filter_depo_MDS: TwwDataSource;
    List_Filter_Invoice_mkode_filter: TStringField;
    List_Filter_Invoice_mKeterangan: TStringField;
    List_Filter_InvoiceKODE_FILTER: TStringField;
    List_Filter_Invoice_mis_negasi: TStringField;
    List_Filter_Invoice_user: TUniQuery;
    List_Filter_Invoice_userNAMA_USER: TStringField;
    List_Filter_Invoice_userPASSCODE: TStringField;
    List_Filter_Invoice_userNAMA_LENGKAP: TStringField;
    List_Filter_Invoice_userKETERANGAN: TStringField;
    List_Filter_Invoice_userkode_Filter: TStringField;
    List_Filter_Invoice_userDS: TwwDataSource;
    List_Filter_Invoiceexc_list_filter: TStringField;
    Mlist_Stock_Point: TUniTable;
    Mlist_Stock_PointDS: TwwDataSource;
    Mlist_Stock_PointSALESPOINTCD: TStringField;
    Mlist_Stock_PointSTOCKPOINTNAME: TStringField;
    Mlist_Stock_Pointkode_sp_po: TStringField;
    MGroup_Material: TUniTable;
    MGroup_MaterialDS: TwwDataSource;
    MGroup_MaterialMaterial_cd: TStringField;
    MGroup_MaterialMaterial_Nama: TStringField;
    MGroup_MaterialGroup_Material: TStringField;
    MList_Branch: TUniQuery;
    MList_BranchDS: TwwDataSource;
    MST_Customer_DS: TwwDataSource;
    Mst_customer: TUniQuery;
    Mst_customerCODE: TStringField;
    Mst_customernama: TStringField;
    Mst_customerunk1: TStringField;
    Mst_customershort_nama: TStringField;
    Mst_customerbill_to_nama: TStringField;
    Mst_customercontact_person: TStringField;
    Mst_customerunk2: TStringField;
    Mst_customeradress: TStringField;
    Mst_customerunk3: TStringField;
    Mst_customercust_group: TStringField;
    Mst_customerphone: TStringField;
    Mst_customerpost_code: TStringField;
    Mst_customerkota: TStringField;
    Mst_customerprice_level: TStringField;
    Mst_customeroutlet_type: TStringField;
    Mst_customerterm: TStringField;
    Mst_customertax_code: TStringField;
    Mst_customerprint_fp: TStringField;
    Mst_customerstockpoint_code: TStringField;
    Mst_customerkode_branch: TStringField;
    Mst_customerPertanggal: TDateField;
    Mst_customerkelurahan_nama: TStringField;
    Mst_customerkecamatan_nama: TStringField;
    Mst_customerkelurahan_cd: TStringField;
    m_material: TUniQuery;
    m_materialDS: TwwDataSource;
    m_materialMaterial_cd: TStringField;
    m_materialMaterial_Nama: TStringField;
    m_materialGroup_Material: TStringField;
    m_materialuom_1: TStringField;
    m_materialuom_2: TStringField;
    m_materialKonversi: TFloatField;
    m_materialBrand: TStringField;
    Mst_customer_max: TUniQuery;
    StringField2: TStringField;
    StringField39: TStringField;
    StringField40: TStringField;
    StringField41: TStringField;
    StringField42: TStringField;
    StringField43: TStringField;
    StringField44: TStringField;
    StringField45: TStringField;
    StringField46: TStringField;
    StringField47: TStringField;
    StringField48: TStringField;
    StringField49: TStringField;
    StringField50: TStringField;
    StringField51: TStringField;
    StringField52: TStringField;
    StringField61: TStringField;
    StringField62: TStringField;
    StringField63: TStringField;
    StringField64: TStringField;
    StringField65: TStringField;
    DateField3: TDateField;
    StringField66: TStringField;
    StringField67: TStringField;
    StringField68: TStringField;
    Mst_customer_maxSTOCKPOINTNAME: TStringField;
    Mst_customer_maxnama_Branch: TStringField;
    Mst_customer_maxJenis_Tier: TStringField;
    Mst_customer_maxOutlet_type_list: TStringField;
    Mst_customer_maxPrice_Level_list: TStringField;
    Mst_customer_maxDS: TwwDataSource;
    Mlist_Stock_Pointkode_branch: TStringField;
    Mlist_Stock_PointSALESPOINTCD_Con: TStringField;
    Mlist_Stock_Pointnama_Branch: TStringField;
    Mlist_Stock_PointPrimary_key: TStringField;
    Mst_customer_maxkredit_limit: TLargeintField;
    MList_Branchkode_branch: TWideStringField;
    MList_Branchnama_Branch: TWideStringField;
    m_materialJENIS: TStringField;
    m_materialGroup_1: TWideStringField;
    Material_Group: TUniQuery;
    StringField55: TStringField;
    Material_GroupDS: TwwDataSource;
    m_materialis_show: TWideStringField;
    m_materialno_urut: TIntegerField;
    Mst_Cust_TMP: TUniTable;
    Mst_Cust_TMPDS: TwwDataSource;
    Mst_Cust_TMPShip_code: TWideStringField;
    Mst_Cust_TMPShip_desc: TWideStringField;
    Mst_Cust_TMPAdress: TWideStringField;
    Mst_Cust_TMPCity: TWideStringField;
    Mst_Cust_TMPPilar: TWideStringField;
    Mst_Cust_TMP_Kontribusi: TUniTable;
    Mst_Cust_TMP_KontribusiDS: TwwDataSource;
    Mst_Cust_TMP_KontribusiBRANCH: TWideStringField;
    Mst_Cust_TMP_KontribusiPilar: TWideStringField;
    Mst_Cust_TMP_KontribusiBRANCH_NAMA: TWideStringField;
    Mst_Cust_TMP_KontribusikONTRIBUSI_procent: TFloatField;
    m_materialBrand_Group: TStringField;
    Mlist_Plant: TUniQuery;
    Mlist_PlantDS: TwwDataSource;
    Mlist_PlantPlant: TWideStringField;
    Mlist_PlantKODE_SAP: TWideStringField;
    Mlist_Plantnama_Plant: TWideStringField;
    Mlist_PlantBRANCH: TWideStringField;
    Mlist_PlantNama_Branch: TWideStringField;
    Mlist_PlantSUPPORTED_KETERANGAN: TWideStringField;
    Mlist_PlantGROUPING: TWideStringField;
    Mlist_PlantKODE_SHIP_TO: TWideStringField;
    Mlist_Plantkode_Sap_2: TWideStringField;
    Mst_reason_Recon: TUniTable;
    wwDataSource2: TwwDataSource;
    Mst_reason_Reconketerangan: TWideStringField;
    Mst_reason_Reconis_active: TWideStringField;
    MProductID_ITEM: TIntegerField;
    MProductis_inv_non_sap: TWideStringField;
    MProductis_asset_non_capex: TWideStringField;
    M_Grouping_MaterialDS: TwwDataSource;
    M_Grouping_Material: TUniQuery;
    M_Grouping_MaterialGrouping: TWideStringField;
    M_Bom: TUniQuery;
    M_BomDS: TwwDataSource;
    M_BomMaterial_number: TWideStringField;
    M_Bommaterial_desc: TWideStringField;
    M_BomAlternative_bom: TWideStringField;
    M_Bomplant: TWideStringField;
    M_Bombase_qty: TFloatField;
    M_Bombase_uom: TWideStringField;
    M_Bombom_component: TWideStringField;
    M_Bomcomponent_desc: TWideStringField;
    M_Bommaterial_group: TWideStringField;
    M_Bomcomponent_qty: TFloatField;
    M_Bomcomponent_uom: TWideStringField;
    M_Bomstatus_bom: TWideStringField;
    m_material_RM: TUniQuery;
    m_material_RMDS: TwwDataSource;
    m_material_RMMaterial_Nama: TStringField;
    m_material_RMGroup_Material_1: TStringField;
    m_material_RMGroup_Material_2: TStringField;
    m_material_RMGroup_AMDK: TStringField;
    m_material_RMuom_1: TStringField;
    m_material_RMuom_2: TStringField;
    m_material_RMKonversi: TFloatField;
    m_material_RMJENIS: TStringField;
    m_material_RMis_show: TWideStringField;
    m_material_RMno_urut: TIntegerField;
    m_material_RMBrand_Group: TStringField;
    Mproduct_max: TUniQuery;
    Mproduct_maxmax_c: TIntegerField;
    MPlant: TUniTable;
    MPlantDS: TwwDataSource;
    m_materialGross_Weight: TFloatField;
    Jns_tra_doc: TUniQuery;
    Jns_tra_docDS: TwwDataSource;
    Jns_tra_docJenis: TWideStringField;
    Jns_tra_docGroup_jenis: TWideStringField;
    Jns_tra_docId_Transaksi_D: TIntegerField;
    Jns_tra_docCket: TStringField;
    MPlantBRANCH: TWideStringField;
    MPlantKODE_SAP: TWideStringField;
    MPlantKETERANGAN: TWideStringField;
    MPlantSUPPORTED_BRANCH: TWideStringField;
    MPlantSUPPORTED_KETERANGAN: TWideStringField;
    MPlantGROUPING: TWideStringField;
    MPlantKODE_SHIP_TO: TWideStringField;
    MPlantkode_Sap_2: TWideStringField;
    MPlantkode_sap_2_nama: TWideStringField;
    MPlantMAP_PLANT: TWideStringField;
    MPlantNama_Origin: TWideStringField;
    MPlantSUPPLY_PLANT_KD: TWideStringField;
    MPlantvisible: TWideStringField;
    MPlantBatch_CD: TWideStringField;
    MPlantSetting_Planning: TWideStringField;
    MPlantBranch_Origin: TWideStringField;
    MPlantBUM: TWideStringField;
    MPlantNama_Koneksi: TWideStringField;
    MPlantPlant_Claim: TWideStringField;
    m_material_RMMaterial_cd: TWideStringField;
    MProductKLASIFIKASI: TWideStringField;
    MProductKODE_ITEM: TWideStringField;
    MPlantalamat1: TWideStringField;
    MPlantalamat2: TWideStringField;
    MPlantalamat3: TWideStringField;
    MPlanttelp1: TWideStringField;
    MPlanttelp2: TWideStringField;
    MST_Vendor_ttf: TUniTable;
    MST_Vendor_ttfDS: TwwDataSource;
    MST_Vendor_ttfBranch: TWideStringField;
    MST_Vendor_ttfKode_Vendor: TIntegerField;
    MST_Vendor_ttfNama_Vendor: TWideStringField;
    MST_Vendor_ttfAlamat_vendor: TWideStringField;
    MST_Vendor_ttfno_WA: TWideStringField;
    MST_Vendor_ttfAlamat_email: TWideStringField;
    MST_Vendor_ttfKode_Vendor_sap: TWideStringField;
    ZMUSERTRENAMA_USER: TStringField;
    ZMUSERTREPASSCODE: TStringField;
    ZMUSERTRENAMA_LENGKAP: TStringField;
    ZMUSERTREKETERANGAN: TStringField;
    ZMUSERTREIS_ADMIN: TStringField;
    ZMUSERTRETGL_EXPIRED: TDateTimeField;
    ZMUSERTREIS_VALUE: TStringField;
    ZMUSERTREIS_MANAGE: TStringField;
    ZMUSERTRELEVEL_USER: TIntegerField;
    ZMUSERTREIS_LOKAL: TStringField;
    ZMUSERTRENIK: TStringField;
    ZMUSERTREAll_depo: TStringField;
    ZMUSERTREis_alfa: TStringField;
    ZMUSERTREkode_Filter: TStringField;
    ZMUSERTREmcadress: TStringField;
    ZMUSERTREbranch: TStringField;
    ZMUSERTREFolder_Update: TWideStringField;
    ZMUSERTREScan_Bagian: TWideStringField;
    ZMUSERTRENAMA: TStringField;
    ZMUSERTREBAGIAN: TStringField;
    procedure MbankAfterPost(DataSet: TDataSet);
    procedure MKotaAfterPost(DataSet: TDataSet);
    procedure MProductNewRecord(DataSet: TDataSet);
    procedure MWilayahNewRecord(DataSet: TDataSet);
    procedure mst_outletNewRecord(DataSet: TDataSet);
    procedure MST_OUTLETBeforeOpen(DataSet: TDataSet);
    procedure MkendaraanBeforeOpen(DataSet: TDataSet);
    procedure MkendaraanNewRecord(DataSet: TDataSet);
    procedure Lks_gudangNewRecord(DataSet: TDataSet);
    procedure Lks_gudangBeforeOpen(DataSet: TDataSet);
    procedure MaccountNewRecord(DataSet: TDataSet);
    procedure Mbiaya_pendapatanNewRecord(DataSet: TDataSet);
    procedure MST_SUPPLIERNewRecord(DataSet: TDataSet);
    procedure List_Filter_Invoice_mNewRecord(DataSet: TDataSet);
    procedure Jns_tra_docCalcFields(DataSet: TDataSet);
    procedure Mproduct_maxBeforePost(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  _DataModuleMaster: T_DataModuleMaster;

implementation

uses DataModule;

{$R *.dfm}

procedure T_DataModuleMaster.MbankAfterPost(DataSet: TDataSet);
begin
  Mbank.Refresh;
end;

procedure T_DataModuleMaster.MKotaAfterPost(DataSet: TDataSet);
begin
MKota.Refresh;
end;

procedure T_DataModuleMaster.MProductNewRecord(DataSet: TDataSet);
begin

  MProductIS_AKTIF.AsString:='T';
  MProductis_inv_non_sap.AsString:='1';
  MProductis_asset_non_capex.AsString:='0';


end;

procedure T_DataModuleMaster.MWilayahNewRecord(DataSet: TDataSet);
begin
   MWilayahdepo.AsString:=_DataModule.Vdepo;
end;

procedure T_DataModuleMaster.mst_outletNewRecord(DataSet: TDataSet);
begin
   mst_outletis_aktif.AsString:='T';
   mst_outletKREDIT_LIMIT.AsInteger:=0;
   mst_outletis_black_list.AsString:='F';
   MST_OUTLETis_tunai.AsString:='F';
   mst_outletIS_ALAMAT_KIRIM_SAMA.AsString:='T';
   mst_outletdepo.AsString:=_DataModule.Vdepo;
   mst_outletKODE_TRANSAKSI_PAJAK.AsString:='PKP : 01';


end;

procedure T_DataModuleMaster.MST_OUTLETBeforeOpen(DataSet: TDataSet);
begin
 //    MST_OUTLET.ParamByName('0').AsString:=_DataModule.Vdepo;
end;

procedure T_DataModuleMaster.MkendaraanBeforeOpen(DataSet: TDataSet);
begin
  //   Mkendaraan.ParamByName('0').AsString:=_DataModule.Vdepo;
end;

procedure T_DataModuleMaster.MkendaraanNewRecord(DataSet: TDataSet);
begin
 // Mkendaraandepo.AsString:=_DataModule.Vdepo;
  MkendaraanIS_AKTIF.AsString:='T';
  Mkendaraansts_kepemilikan.AsString:='T';
end;

procedure T_DataModuleMaster.Lks_gudangNewRecord(DataSet: TDataSet);
begin
  Lks_gudangdepo.AsString:=_DataModule.Vdepo;
  Lks_gudangIS_AKTIF.AsString:='T';

end;

procedure T_DataModuleMaster.Lks_gudangBeforeOpen(DataSet: TDataSet);
begin
     Lks_gudang.ParamByName('0').AsString:=_DataModule.Vdepo;
end;

procedure T_DataModuleMaster.MaccountNewRecord(DataSet: TDataSet);
begin
   Maccountis_aktif.AsString:='T';
   Maccountcost_center.AsString:='F';
   Maccountproyek.AsString:='F';
   Maccounttipe.AsString:='ASSET';
end;

procedure T_DataModuleMaster.Mbiaya_pendapatanNewRecord(DataSet: TDataSet);
begin
   Mbiaya_pendapatanis_aktif.AsString:='T';

end;

procedure T_DataModuleMaster.MST_SUPPLIERNewRecord(DataSet: TDataSet);
begin
  MST_SUPPLIERis_aktif.AsString:='T';
end;

procedure T_DataModuleMaster.List_Filter_Invoice_mNewRecord(
  DataSet: TDataSet);
begin
  List_Filter_Invoice_mis_negasi.AsString:='0';
end;

procedure T_DataModuleMaster.Jns_tra_docCalcFields(DataSet: TDataSet);
begin
  Jns_tra_docCket.AsString:=Jns_tra_docJenis.AsString+' - '+ Jns_tra_docGroup_jenis.asstring;
end;

procedure T_DataModuleMaster.Mproduct_maxBeforePost(DataSet: TDataSet);
begin
  if    MProductID_ITEM.asstring='' then
  begin
  Mproduct_max.close;
  Mproduct_max.open;
  MProductID_ITEM.AsInteger:=Mproduct_maxmax_c.AsInteger;
  end;
  if  MProductKODE_ITEM.asstring='' then
      MProductKODE_ITEM.asstring:=MProductID_ITEM.asstring;
end;

end.
